/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Config.ConfigSession;
import Hibernate.Saldo;
import Hibernate.Transaksi;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Iterator;
import java.util.List;
import javafx.util.converter.LocalDateStringConverter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.transaction.Transactional;
import net.sf.ehcache.search.Results;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.SQLQuery;
import org.hibernate.Session;

/**
 *
 * @author GEMBUL
 */
public class InsertTransaksi extends javax.swing.JDialog {

    /**
     * Creates new form InsertSaldo
     */
    String sql;

    public InsertTransaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        SettingTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jidInsTrans = new javax.swing.JTextField();
        jid_saldoInsTrans = new javax.swing.JTextField();
        jnominalInsTrans = new javax.swing.JTextField();
        insertTanggal = new javax.swing.JLabel();
        jjenisInsTrans = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        insertInsTrans = new javax.swing.JButton();
        bersihInsTrans = new javax.swing.JButton();
        kembaliInsTrans = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("INSERT TRANSAKSI");

        jLabel2.setText("KODE TRANSAKSI");

        jLabel3.setText("ID NASABAH");

        jLabel4.setText("NOMINAL");

        insertTanggal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        insertTanggal.setText("TANGGAL");
        insertTanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                insertTanggalPropertyChange(evt);
            }
        });

        jjenisInsTrans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kredit", "Debet" }));

        jLabel6.setText("JENIS TRANSAKSI");

        insertInsTrans.setText("INSERT");
        insertInsTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertInsTransActionPerformed(evt);
            }
        });

        bersihInsTrans.setText("CLEAR");
        bersihInsTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihInsTransActionPerformed(evt);
            }
        });

        kembaliInsTrans.setText("BACK");
        kembaliInsTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliInsTransActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("TR-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("ID-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jjenisInsTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jnominalInsTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jid_saldoInsTrans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(jidInsTrans, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(insertTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(kembaliInsTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bersihInsTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertInsTrans)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(insertTanggal)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jidInsTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jid_saldoInsTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnominalInsTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjenisInsTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertInsTrans)
                    .addComponent(bersihInsTrans)
                    .addComponent(kembaliInsTrans))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void bersihInsTransActionPerformed(java.awt.event.ActionEvent evt) {                                               
        jidInsTrans.setText(null);
        jid_saldoInsTrans.setText(null);
        jnominalInsTrans.setText(null);
        jjenisInsTrans.setSelectedItem(null);
        // TODO add your handling code here:
    }                                              

    private void kembaliInsTransActionPerformed(java.awt.event.ActionEvent evt) {                                                
        new MainMenu().setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }                                               

    private void insertTanggalPropertyChange(java.beans.PropertyChangeEvent evt) {                                             

        // TODO add your handling code here:
    }                                            
    @Transactional
    private void insertInsTransActionPerformed(java.awt.event.ActionEvent evt) {                                               
        Transaksi b = new Transaksi();
        b.setId("TR-" + jidInsTrans.getText());
        b.setNominal(Float.parseFloat(jnominalInsTrans.getText()));
        b.setJenis(jjenisInsTrans.getSelectedItem().toString());
        b.setId_saldo("ID-" + jid_saldoInsTrans.getText());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss");
        LocalDateTime sekarang = LocalDateTime.now();
        Timestamp ts = Timestamp.valueOf(sekarang);
        b.setTanggal(ts);
        try {
            Session session = ConfigSession.getSessionFactory().openSession();
            session.beginTransaction();
            session.save(b);
            session.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "Tambah Berhasil");
        } catch (HibernateException he) {
            JOptionPane.showMessageDialog(this, "Tambah Gagal");
            he.printStackTrace();
        }

        // UPDATE TABEL SALDO WITH NATIVE SQL
        try {
            Connection koneksi = DriverManager.getConnection("jdbc:postgresql://localhost:5432/bcaf?zeroDateTimeBehavior=convertToNull", "postgres", "rojam456");
            if (jjenisInsTrans.getSelectedItem().toString().equalsIgnoreCase("Kredit")) {
                sql = "UPDATE SALDO SET TOTAL_SALDO = TOTAL_SALDO+" + jnominalInsTrans.getText() + " WHERE ID_SALDO = 'ID-" + jid_saldoInsTrans.getText() + "'";
            } else {
                sql = "UPDATE SALDO SET TOTAL_SALDO = TOTAL_SALDO-" + jnominalInsTrans.getText() + " WHERE ID_SALDO = 'ID-" + jid_saldoInsTrans.getText() + "'";
            }
            PreparedStatement ps = koneksi.prepareStatement(sql);
            ps.executeUpdate();
        } catch (SQLException ex) {
            System.err.println("Database tidak ditemukan!");
        }

        // TODO add your handling code here:
    }                                              

    public void SettingTanggal() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss");
        LocalDateTime sekarang = LocalDateTime.now();
        insertTanggal.setText(dtf.format(sekarang));
        System.out.println(dtf.format(sekarang));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InsertTransaksi dialog = new InsertTransaksi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bersihInsTrans;
    private javax.swing.JButton insertInsTrans;
    private javax.swing.JLabel insertTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jidInsTrans;
    private javax.swing.JTextField jid_saldoInsTrans;
    private javax.swing.JComboBox<String> jjenisInsTrans;
    private javax.swing.JTextField jnominalInsTrans;
    private javax.swing.JButton kembaliInsTrans;
    // End of variables declaration                   
}
